// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6h7coXfl-2X8KMbcIEYaguc9rvoZCAhU',
    appId: '1:681275256059:web:6f1575d8517ea50a83945e',
    messagingSenderId: '681275256059',
    projectId: 'smartcryptology',
    authDomain: 'smartcryptology.firebaseapp.com',
    storageBucket: 'smartcryptology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnwY6f_C1wnxdcDBer3ri6Z_l39mrfk5M',
    appId: '1:681275256059:android:4719f2ffdecaa88783945e',
    messagingSenderId: '681275256059',
    projectId: 'smartcryptology',
    storageBucket: 'smartcryptology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFlABM1Dl_rrlS8wqgFd30zVP-TWZQeE',
    appId: '1:681275256059:ios:7a65b54e03db8c6683945e',
    messagingSenderId: '681275256059',
    projectId: 'smartcryptology',
    storageBucket: 'smartcryptology.appspot.com',
    iosBundleId: 'com.example.smartcryptology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFlABM1Dl_rrlS8wqgFd30zVP-TWZQeE',
    appId: '1:681275256059:ios:7a65b54e03db8c6683945e',
    messagingSenderId: '681275256059',
    projectId: 'smartcryptology',
    storageBucket: 'smartcryptology.appspot.com',
    iosBundleId: 'com.example.smartcryptology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6h7coXfl-2X8KMbcIEYaguc9rvoZCAhU',
    appId: '1:681275256059:web:24d4341ef03ce68583945e',
    messagingSenderId: '681275256059',
    projectId: 'smartcryptology',
    authDomain: 'smartcryptology.firebaseapp.com',
    storageBucket: 'smartcryptology.appspot.com',
  );
}
